import type { UsersWithRole } from "./types"

export const mockUsers: UsersWithRole[] = [
  {
    id: "1",
    nom: "Dubois",
    prenom: "Marie",
    email: "marie.dubois@example.com",
    telephone: "+33 6 12 34 56 78",
    avatarUrl: "/woman-doctor.png",
    dateNaissance: new Date("1985-03-15"),
    status: "ACTIF",
    createdAt: new Date("2023-01-10"),
    updatedAt: new Date("2024-01-15"),
    role: "MEDECIN",
    medecin: {
      numLicence: "MED-2023-001",
      statut: "APPROUVE",
      specialite: {
        nom: "Cardiologie",
      },
    },
    patient: null,
  },
  {
    id: "2",
    nom: "Martin",
    prenom: "Jean",
    email: "jean.martin@example.com",
    telephone: "+33 6 23 45 67 89",
    avatarUrl: "/man-patient.png",
    dateNaissance: new Date("1990-07-22"),
    status: "ACTIF",
    createdAt: new Date("2023-02-20"),
    updatedAt: new Date("2024-02-10"),
    role: "PATIENT",
    medecin: null,
    patient: {
      groupeSanguin: "A_POSITIF",
      sexe: "Homme",
    },
  },
  {
    id: "3",
    nom: "Lefebvre",
    prenom: "Sophie",
    email: "sophie.lefebvre@example.com",
    telephone: "+33 6 34 56 78 90",
    avatarUrl: "/woman-doctor.png",
    dateNaissance: new Date("1988-11-05"),
    status: "ACTIF",
    createdAt: new Date("2023-03-15"),
    updatedAt: new Date("2024-03-01"),
    role: "MEDECIN",
    medecin: {
      numLicence: "MED-2023-002",
      statut: "APPROUVE",
      specialite: {
        nom: "Pédiatrie",
      },
    },
    patient: null,
  },
  {
    id: "4",
    nom: "Bernard",
    prenom: "Pierre",
    email: "pierre.bernard@example.com",
    telephone: null,
    avatarUrl: null,
    dateNaissance: new Date("1975-04-18"),
    status: "PENDING",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
    role: "MEDECIN",
    medecin: {
      numLicence: "MED-2024-003",
      statut: "EN_ATTENTE",
      specialite: {
        nom: "Neurologie",
      },
    },
    patient: null,
  },
  {
    id: "5",
    nom: "Petit",
    prenom: "Claire",
    email: "claire.petit@example.com",
    telephone: "+33 6 45 67 89 01",
    avatarUrl: "/woman-patient.png",
    dateNaissance: new Date("1995-09-30"),
    status: "ACTIF",
    createdAt: new Date("2023-05-12"),
    updatedAt: new Date("2024-01-20"),
    role: "PATIENT",
    medecin: null,
    patient: {
      groupeSanguin: "O_NEGATIF",
      sexe: "Femme",
    },
  },
  {
    id: "6",
    nom: "Moreau",
    prenom: "Thomas",
    email: "thomas.moreau@example.com",
    telephone: "+33 6 56 78 90 12",
    avatarUrl: "/man-admin.jpg",
    dateNaissance: new Date("1982-12-08"),
    status: "ACTIF",
    createdAt: new Date("2022-11-01"),
    updatedAt: new Date("2024-02-28"),
    role: "ADMIN",
    medecin: null,
    patient: null,
  },
  {
    id: "7",
    nom: "Laurent",
    prenom: "Isabelle",
    email: "isabelle.laurent@example.com",
    telephone: "+33 6 67 89 01 23",
    avatarUrl: "/woman-patient.png",
    dateNaissance: new Date("1992-06-14"),
    status: "INACTIF",
    createdAt: new Date("2023-08-22"),
    updatedAt: new Date("2023-12-15"),
    role: "PATIENT",
    medecin: null,
    patient: {
      groupeSanguin: "B_POSITIF",
      sexe: "Femme",
    },
  },
  {
    id: "8",
    nom: "Simon",
    prenom: "Luc",
    email: "luc.simon@example.com",
    telephone: "+33 6 78 90 12 34",
    avatarUrl: "/man-doctor.png",
    dateNaissance: new Date("1980-02-25"),
    status: "ACTIF",
    createdAt: new Date("2023-04-18"),
    updatedAt: new Date("2024-03-10"),
    role: "MEDECIN",
    medecin: {
      numLicence: "MED-2023-004",
      statut: "APPROUVE",
      specialite: {
        nom: "Orthopédie",
      },
    },
    patient: null,
  },
]
